driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: debian-7.11
  - name: debian-8.8
  - name: debian-9.0
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list: test::default
# could run the cookbooks default recipe, if nothing else to make sure it doesn't error out immediately
# Need the inspec tests.  domain and user resources.
